USER_ROLE_SUPERUSER = 1
USER_ROLE_GUEST = 2
USER_ROLES = (
    (USER_ROLE_SUPERUSER, 'SuperAdmin'),
    (USER_ROLE_GUEST, 'Guest')
)

JOURNAL_TYPE_BULLET = 1
JOURNAL_TYPE_FOOD = 2
JOURNAL_TYPE_TRAVEL = 3
JOURNAL_TYPE_SPORT = 4
JOURNAL_TYPES = (
    (JOURNAL_TYPE_BULLET , 'Bullet'),
    (JOURNAL_TYPE_FOOD , 'Food'),
    (JOURNAL_TYPE_TRAVEL , 'Travel'),
    (JOURNAL_TYPE_SPORT, 'Sport')
)