# Generated by Django 3.1.6 on 2021-03-20 05:08

import auth_.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0002_mainuser_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mainuser',
            managers=[
                ('objects', auth_.models.MainUserManager()),
            ],
        ),
    ]
