# Generated by Django 3.1.6 on 2021-03-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0004_auto_20210320_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='is_stuff',
            field=models.BooleanField(default=True, verbose_name='staff'),
        ),
    ]
