# Generated by Django 3.1.6 on 2021-03-20 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0005_auto_20210320_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainuser',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
