# Generated by Django 3.1.6 on 2021-03-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Book name')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('description', models.TextField(blank=True, max_length=300)),
                ('created_at', models.DateField(verbose_name='Дата создания')),
                ('num_pages', models.IntegerField(verbose_name='Pages')),
                ('genre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Genre')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Book name')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('description', models.TextField(blank=True, max_length=300)),
                ('created_at', models.DateField(verbose_name='Дата создания')),
                ('type', models.SmallIntegerField(choices=[(1, 'Bullet'), (2, 'Food'), (3, 'Travel'), (4, 'Sport')], default=1)),
                ('publisher', models.CharField(blank=True, max_length=30, null=True, verbose_name='publisher')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'abstract': False,
            },
        ),
    ]
