# Generated by Django 3.1.6 on 2021-03-20 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'Jounral', 'verbose_name_plural': 'Journals'},
        ),
    ]
